name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure base path based on environment
      - name: Configure base path
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo 'baseurl: "/venue-playlists"' > website/_config.yml
          else
            echo 'baseurl: "/venue-playlists/dev"' > website/_config.yml
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
