name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'website/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://mattmock.github.io/venue-playlists
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build prod
        run: |
          mkdir -p website-build
          cp -r website/* website-build/
          echo 'baseurl: "/venue-playlists"' > website-build/_config.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website-build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://mattmock.github.io/venue-playlists/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build dev
        run: |
          mkdir -p website-build/dev
          cp -r website/* website-build/dev/
          echo 'baseurl: "/venue-playlists/dev"' > website-build/dev/_config.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website-build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
