name: Update Venue Data and Deploy

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8am UTC
  workflow_dispatch:      # Allow manual triggers

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create venue config directory
        run: mkdir -p data/venue-data/sf
          
      - name: Update venue data
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/update_all.py --force-all
        
      - name: Commit data changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/venue-data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update venue data [skip ci]" && git push)
          
      - name: Pull latest changes
        run: git pull origin main
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          
      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site